# Generated by Django 2.2.8 on 2020-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title of the section: eg personal info'),
        ),
    ]
