# Generated by Django 2.2.8 on 2020-04-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0003_auto_20200416_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='A sub category for an answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='opinion_aggregator.OptionModel')),
            ],
            options={
                'verbose_name_plural': 'Option sub categories',
            },
        ),
    ]
