# Generated by Django 2.2.8 on 2020-04-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0003_auto_20200414_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='optionmodel',
            name='question',
        ),
    ]
