# Generated by Django 2.2.8 on 2020-04-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0004_auto_20200414_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinion_aggregator.OptionModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='opinion_aggregator.QuestionModel')),
            ],
            options={
                'verbose_name_plural': 'Question Options',
            },
        ),
    ]
