# Generated by Django 2.2.8 on 2020-04-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0004_optionsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionmodel',
            options={'ordering': ('description',), 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='optionsubcategory',
            options={'ordering': ('description',), 'verbose_name_plural': 'Option sub categories'},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ('description',), 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='optionsubcategory',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='opinion_aggregator.QuestionOptions'),
        ),
    ]
