# Generated by Django 2.2.8 on 2020-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0005_questionoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emirates_id',
            field=models.IntegerField(default=123456789767365),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
