# Generated by Django 2.2.8 on 2020-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0005_auto_20200423_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='has_sub_category',
            field=models.BooleanField(default=False, help_text='Designates whether this option has sub categories of answers.', verbose_name='has_subcategories'),
        ),
    ]
