# Generated by Django 2.2.8 on 2020-04-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0006_questionoptions_has_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoptions',
            options={'ordering': ('option',), 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AddField(
            model_name='optionsubcategory',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='opinion_aggregator.QuestionModel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='optionsubcategory',
            unique_together={('description', 'option')},
        ),
    ]
