# Generated by Django 2.2.8 on 2020-04-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0008_remove_optionsubcategory_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponsesmodel',
            name='question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='opinion_aggregator.QuestionOptions'),
        ),
    ]
