# Generated by Django 2.2.8 on 2020-04-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion_aggregator', '0010_remove_surveyresponsesmodel_question_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ('position',), 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='position',
            field=models.IntegerField(blank=True, help_text='Designates the position a question should be in.', null=True),
        ),
    ]
